services:
  - type: web
    name: enterprise-platform-backend
    runtime: docker
    repo: https://github.com/sujaytumu/enterprise-platform
    branch: deploy-free-stack
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: PGHOST
        sync: false
      - key: PGPORT
        sync: false
      - key: PGDATABASE
        sync: false
      - key: PGUSER
        sync: false
      - key: PGPASSWORD
        sync: false
      - key: FRONTEND_ORIGIN
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false

  - type: web
    name: enterprise-platform-frontend
    runtime: static
    repo: https://github.com/sujaytumu/enterprise-platform
    branch: deploy-free-stack
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
