server:
  port: ${PORT:8080}

spring:
  application:
    name: enterprise-platform-backend
  datasource:
    # url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:enterprise}
    url: jdbc:postgresql://ep-small-bonus-awhskmzk-pooler.c-12.us-east-1.aws.neon.tech/payments?

    SPRING_DATASOURCE_USERNAME = payments_owner
    SPRING_DATASOURCE_PASSWORD = npg_0wkJuQbeNIf1
    # username: ${PGUSER:postgres}
    # password: ${PGPASSWORD:postgres}
  

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
    
      hibernate:
        format_sql: false

app:
  frontend-origin: ${FRONTEND_ORIGIN:*}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always